### ISSUE TITLE
[Epic]: delegate native logics to Finschia/cosmos-sdk

### ISSUE THREAD

**Issue by 0Tech** [Finschia/finschia-sdk#1195]
### Summary

From now, this repository will only maintain its original modules. Others like cosmos native logic and core logic developed by Finschia dev would be migrated to Finschia/cosmos-sdk.

### Problem Definition

Refer: Finschia/cosmos-sdk#1

### Work Breakdown

- [ ] Delegate native logics to Finschia/cosmos-sdk
- [ ] Update x/token to use Finschia/cosmos-sdk@v0.50.2
- [ ] Update x/collection to use Finschia/cosmos-sdk@v0.50.2
- [ ] Update x/foundation to use Finschia/cosmos-sdk@v0.50.2
- [ ] Stop using of x/params in x/token
- [ ] Stop using of x/params in x/collection
- [ ] Stop using of x/params in x/foundation
- [ ] Use x/collections (c.f. not x/collection, it's cosmos native feature) in x/foundation

The works would be first merged onto a feature branch `bumpup50`. After finishing internal audit, it would be finally merged onto `main`.
